export const SET_ALL_PRODUCTS_CONTENT = 'SET_ALL_PRODUCTS_CONTENT';
export const SET_SELECTED_PRODUCT_CONTENT = 'SET_SELECTED_PRODUCT_CONTENT';
export const REMOVE_SELECTED_PRODUCT_CONTENT = 'REMOVE_SELECTED_PRODUCT_CONTENT';
export const FETCH_ALL_PRODUCTS_CONTENT = 'FETCH_ALL_PRODUCTS_CONTENT';
export const FETCH_SELECTED_PRODUCT_CONTENT = 'FETCH_SELECTED_PRODUCT_CONTENT';
